### ISSUE TITLE
Attempted to call function "putenv" from namespace "Symfony\Component\HttpKernel"

### ISSUE THREAD

**Issue by ondrastarek** [mcdeck/netlify-cms-oauth-provider-php#7]
Hello, 
I am trying to implement this oauth to my application, but I have an error with Symfony and I have no idea where the problem is. Error message looks like this: 
![image](https://user-images.githubusercontent.com/45853735/151669384-171c3ef0-f0ad-468f-ae88-fc50dec3e45e.png)

my .env.local looks like this:

`OAUTH_CLIENT_ID=xxxxx
OAUTH_CLIENT_SECRET=xxx
REDIRECT_URI=http://auth.ondrejstarek.site/callback
ORIGIN=http://ondrejstarek.site
`
I have also this in my .env file.

I am quite confused and without any clue of whats wrong. Thank you for any help!

**Comment by ondrastarek** [comment]
That was actually because of putenv, but now there is some problem with annotations.xml
![image](https://user-images.githubusercontent.com/45853735/151873770-7806e7b7-c41e-490f-a012-180756d584d8.png)

**Comment by mcdeck** [comment]
I have not seen this error before and I lack a bit of context as well.

What exactly are you trying to do? 
What is your deployment environment?
Did you follow the README?
Which steps led you to this failure?

**Comment by ondrastarek** [comment]
I am trying to just view my prepared auth page: https://auth.ondrejstarek.site/ just like yours https://www.auth.van-porten.de/
I followed README as best as I could.
First of all, when I do "composer install" there is an error with "putenv" method, I red that this has been depricated due to security reasons, so I commented that line in vendor\symfony\http-kernel\Kernel.php at 774 line.
After this, there is some problem with annotations.xml which you can see in this picture.
About environment, simple webhosting with PHP 7.3 currently, but can be upgraded anytime. All files pushing via FTP.

**Comment by ondrastarek** [comment]
> 

Currently I've uploaded pure install to my FTP and there is this "putenv" problem, which can fixed by commenting, but I am not sure if that is the right way.

**Comment by mcdeck** [comment]
Commenting out code is most likely not the right way. Can you paste the error message you get from `composer install`? That has to work properly.

Also, can you paste the output from `composer --version` and `php --version`? What OS are you on?

**Comment by ondrastarek** [comment]
after `composer install`: there is one confirmation, where I hit the yes option:
![image](https://user-images.githubusercontent.com/45853735/152640202-ef661c71-8941-493c-82ca-f824f3c7a551.png)
after that:
![image](https://user-images.githubusercontent.com/45853735/152640134-75f9f433-c4e3-4f5d-a4f9-ad9c98acc356.png)

`composer --version`: Composer version 2.2.5 2022-01-21 17:25:52
`php --version`: PHP 8.1.2 (cli) (built: Jan 19 2022 10:18:23) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies

**Comment by mcdeck** [comment]
I really have no clue. So I will make a few educated guesses.

Can you try setting `APP_ENV=prod` in your .env file?
If I read the documentation correctly, dev/test environment will by default have debug enabled, and I think that is the problem.

There is debugging code that executes `putenv` which in turn seems to be disabled by your hosting provider (and not by mine, incidentally, which is why I never realized the problem).

If that does not work, try running `symfony server:start` and see if that at least works locally (then it will be something with your provider for sure). Also, I am using PHP 7.4, maybe that is also something to try if all else fails.

**Comment by ondrastarek** [comment]
That was it!
thank you so much sir! :-) 
if anyone gets these errors, you need to do clean `git clone`, after that you must change the `ÀPP_ENV` to `prod`. Only after that you can do `composter install` if you install it before changing environment, you will somehow cause the errors.
For my specific provider environment, I must commented in `public/.htaccess` lines 16,17 and 18. 
`
<IfModule mod_negotiation.c>
    Options -MultiViews
</IfModule>
`

after that, only thing that remains, is create new `.htaccess` in your root folder and into this put:
`RewriteEngine On
RewriteRule (.*) public/$1 [L]
`
that will redirect all to your public folder where is your index.php.

What is what i had must do :-)
