### ISSUE TITLE
Fail to Login

### ISSUE THREAD

**Issue by davli921** [mcdeck/netlify-cms-oauth-provider-php#8]
First, Thank you for developing this and sharing it. 

I have a problem completing the authorization after following the steps mentioned in the readme. 

I get this error on the main window: 

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').


​ Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://cms.example.com') does not match the recipient window's origin ('https://www.example.com').
```

The subdomain https://cms.example.com is where I serve this netlify-cms-oauth-provider-php. 

Here's what I have done: 

**config.yml:**                                              
```
backend:
  name: gitlab 
  branch: BranchName 
  repo: user/RepoName
  base_url: http://cms.example.com/
```

**.env** for netlify-cms-oauth-provider-php. 

```
APP_ENV=prod
APP_SECRET=asdasdasczxc12235
OAUTH_PROVIDER=gitlab
SCOPES=api
OAUTH_DOMAIN=https://gitlab.com
OAUTH_CLIENT_ID=asdasdasdxcasd123
OAUTH_CLIENT_SECRET=asdasdasdxcasd123
REDIRECT_URI=https://cms.example.com/callback/
ORIGIN=example.com
```

**Gitlab app:**

```
Callback URL =
https://cms.example.com/callback/
https://cms.example.com/callback

Confidential = No
Scopes = api (Access the authenticated user's API)
```

Steps to reproduce: 
1. Enter https://www.example.com/admin
2. Click on "Login with Gitlab"
3. Popup window opens and is sent to: https://gitlab.com/users/sign_in
4. Login with Gitlab credentials
5. Popup window is redirected to: https://cms.example.com/callback?code=asdfasdfasdf1234&state=123123asdasdazxca
4. Check the console in the main window and find the error:

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').


​ Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://cms.example.com') does not match the recipient window's origin ('https://www.example.com').
```

**Comment by mcdeck** [comment]
In your backend, your base_url says http, can you try using https instead?
Maybe also try removing the trailing slash just for good measure.

So put this in **config.yaml**:
```yaml
backend:
  [...]
  base_url: https://cms.example.com
```

I think I have seen this issue before, and I think it was somehow configuration related. I will try to reproduce if my suggestion above does not work.

**Comment by davli921** [comment]
> In your backend, your base_url says http, can you try using https instead? Maybe also try removing the trailing slash just for good measure.
> 
> So put this in **config.yaml**:
> 
> ```yaml
> backend:
>   [...]
>   base_url: https://cms.example.com
> ```
> 
> I think I have seen this issue before, and I think it was somehow configuration related. I will try to reproduce if my suggestion above does not work.

No that did not make the trick. Please let me know if you have another idea on what I can try 🙏

**Comment by davli921** [comment]
Yes, it does work now! 

I am using https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify-cms/ and I had to rebuild the Gatsby application in order for the plugin to use the new settings, that was something I had missed also.
So it might have been working even with the previous settings I posted. 

Thank you for helping out and thanks for the provider! :)
